= Vaadin Spring

include::note.asciidoc[]

During these tutorials we will be solving a number of common problems when using the Vaadin Spring plugin. The principal question we will be addressing is "How do I gain access to Spring features in a Vaadin project?"
At the end of these tutorials you will have learned how to

. Set up a Vaadin Spring project using Spring Boot
. Create UI's and Views with Vaadin Spring
. Use injection with standard and Vaadin Spring scopes
. Set up a Vaadin Spring project without Spring Boot

We will assume familiarity with Vaadin 7 and common Spring concepts. As a reference development environment we'll be using Eclipse Luna with the Vaadin plugin, Maven and Tomcat (embedded when using Spring Boot). Installation and configuration of said environment is outside the scope of these tutorials.
The tutorials will build off one another, each starting where the previous left off. Various steps of the tutorial and alternative approaches will in the future be available as tags/branches at https://github.com/vaadin/spring-tutorial.

== Vaadin Spring for the impatient
If you are eager to get started right away without following the tutorial, feel free to do so. There are still some practical details that are good to keep in mind if you're not familiar with Vaadin Spring or Spring in general.

* *Objects must be injected* and managed by Spring in order to use Spring features.
* *Use SpringVaadinServlet and VaadinConfiguration.* When using Spring Boot, these are automatically set up and you don’t need to explicitly set up a servlet. Otherwise, add @EnableVaadin on a @Configuration class and use SpringVaadinServlet.
* *Annotate your UI class with @SpringUI* to let Vaadin Spring know that it should inject and use instances of that class when the application is opened in the browser.
* If you have used vaadin4spring, note that some *annotation and class names have changed*.

=== Related Pages
[upperroman]
. Getting Started with Vaadin Spring and Spring Boot
.. Getting Started with Vaadin Spring and Spring Boot
.. Getting started with Vaadin Spring without Spring Boot
. Injection and Scopes with Vaadin Spring
. Views and Navigation with Vaadin Spring
. Configuring and Using Vaadin Spring without Spring Boot
. Vaadin Spring tips
